# fly.toml app configuration file generated for hub-test-dupa on 2025-03-07T17:46:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hub-test-dupa'
primary_region = 'dfw'
kill_timeout = '2m0s'
swap_size_mb = 2048

[build]
  image = 'ghcr.io/getalby/hub:v1.14.3'

[env]
#  DATABASE_URI = '/data/nwc.db'
  LDK_LOG_LEVEL = '3'
  LOG_LEVEL = '5'
  WORK_DIR = '/data'
  DATABASE_URI = 'postgres://nwc13820861fa:x63Qjndnp2Am@hub-db-lax.internal:5432/nwc13820861fa?sslmode=disable'
  ALBY_OAUTH_CLIENT_ID = 'Q6VIubLWWF'
  ALBY_OAUTH_CLIENT_SECRET = 'jytdjU1uLQyGPlEKwlOW'
  BASE_URL = 'https://my.albyhub.com'
  FLY_PROCESS_GROUP = 'app'
  LDK_ESPLORA_SERVER = 'https://electrs.getalbypro.com'
  LDK_GOSSIP_SOURCE = ''
  LDK_TRANSIENT_NETWORK_GRAPH = 'true'
  LDK_VSS_URL = 'https://vss.getalbypro.com/vss'
  LOG_EVENTS = 'true'
  LOG_TO_FILE = 'false'
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
#  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
